### ISSUE TITLE
Change Which AQI Used From AirNow

### ISSUE THREAD

**Issue by grokdesigns** [ToddGreenfield/homebridge-airnow#3]
I see in the code that the AQI from Ozone is used from AirNow, which shows an Air Quality of 43/Excellent in my dashboard, however, the overall AQI on the AirNow site reflects 110.  Is there a way to change which AQI is used?

**Comment by ToddGreenfield** [comment]
Hi. That is correct, currently the first parameter is used for overall AQI as in my area typically Ozone is used for the AQI (so I thought). After some testing of various zip codes is looks like the API is actually just using the highest number returned from any Ozone, PM2.5 and PM10 (if those are returned). It looks like this should follow that model. Would that work for you?

**Comment by grokdesigns** [comment]
That would be perfect!

**Comment by ToddGreenfield** [comment]
Fixed. Thanks for catching this.
