### ISSUE TITLE
ZIP CODE aqicn_city

### ISSUE THREAD

**Issue by djrams10** [ToddGreenfield/homebridge-airnow#7]
hello, I am looking for the code for my region (@XXXX), but it is impossible to find it with the method of the example. Do you have another solution to find it? I am looking for the code for the region in France / champagne ardenne / Sainte-savine. Thank you in advance.

**Comment by ToddGreenfield** [comment]
You can also search using the map which is what I had to do as I wasn't sure where exactly that was in France. Try 6811 for the code. That is using the location at http://aqicn.org/city/france/champagne-ardenne/troyes/sainte-savine/.
Once the page comes up, scroll down a little bit and you should see a "View the detailed forecast
" button. Hover over that and you can see the code 6811. It takes a little searching to get the code sometimes. Hope this works. Let me know.

**Comment by djrams10** [comment]
hello, thank you very much for your help, thanks to you, it is regulate. have a nice day.
